// src/pages/user/UserAddresses/styles.js

export const getStyles = (isMobile) => ({
  container: {
    fontFamily: '"Inter", sans-serif',
    color: '#1e293b',
  },
  header: {
    marginBottom: isMobile ? '20px' : '32px',
    display: 'flex',
    flexDirection: isMobile ? 'column' : 'row',
    justifyContent: 'space-between',
    alignItems: isMobile ? 'flex-start' : 'center',
    gap: isMobile ? '12px' : '0',
  },
  title: {
    fontSize: isMobile ? '18px' : '20px',
    fontWeight: '700',
    color: '#1e293b',
  },
  addButton: {
    backgroundColor: '#059669',
    color: 'white',
    border: 'none',
    padding: isMobile ? '10px 16px' : '10px 20px',
    borderRadius: '10px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: isMobile ? '13px' : '14px',
    transition: 'background 0.2s',
    width: isMobile ? '100%' : 'auto',
    justifyContent: 'center',
  },
  formCard: {
    backgroundColor: '#f8fafc',
    padding: isMobile ? '16px' : '24px',
    borderRadius: isMobile ? '12px' : '16px',
    border: '1px solid #e2e8f0',
    marginBottom: isMobile ? '16px' : '24px',
  },
  formHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: isMobile ? '16px' : '24px',
  },
  formTitle: {
    fontSize: isMobile ? '14px' : '16px',
    fontWeight: '700',
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: '#059669',
  },
  closeButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#64748b',
  },
  label: {
    display: 'block',
    fontSize: isMobile ? '12px' : '13px',
    fontWeight: '600',
    color: '#475569',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: isMobile ? '10px 12px 10px 32px' : '10px 12px 10px 36px',
    borderRadius: isMobile ? '8px' : '10px',
    border: '1px solid #e2e8f0',
    outline: 'none',
    fontSize: isMobile ? '13px' : '14px',
    transition: 'all 0.2s',
    backgroundColor: 'white',
    boxSizing: 'border-box',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr',
    gap: isMobile ? '12px' : '16px',
    marginBottom: isMobile ? '12px' : '16px',
  },
  addressCard: {
    backgroundColor: 'white',
    padding: isMobile ? '16px' : '20px',
    borderRadius: isMobile ? '12px' : '16px',
    border: '1px solid #e2e8f0',
    marginBottom: isMobile ? '12px' : '16px',
    position: 'relative',
    transition: 'all 0.2s',
  },
  addressCardDefault: {
    border: '2px solid #059669',
    backgroundColor: '#f0fdf4',
  },
  defaultBadge: {
    position: 'absolute',
    top: '-10px',
    right: '16px',
    backgroundColor: '#059669',
    color: 'white',
    padding: isMobile ? '3px 10px' : '4px 12px',
    borderRadius: '12px',
    fontSize: isMobile ? '10px' : '11px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  labelBadge: {
    backgroundColor: '#ecfdf5',
    color: '#059669',
    padding: isMobile ? '3px 8px' : '4px 10px',
    borderRadius: '6px',
    fontSize: isMobile ? '11px' : '12px',
    fontWeight: '600',
  },
  actionButton: {
    padding: isMobile ? '6px' : '8px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingContainer: {
    padding: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200
  },
  spinner: {
    fontSize: 24,
    color: '#059669',
    animation: 'spin 1s linear infinite',
  },
  emptyState: {
    textAlign: 'center',
    padding: '40px 20px',
    backgroundColor: '#f8fafc',
    borderRadius: '16px',
    border: '2px dashed #e2e8f0',
    color: '#64748b',
  },
  inputIcon: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
    fontSize: '14px',
  },
  inputWrapper: {
    position: 'relative',
    width: '100%',
  },
  submitButton: {
    backgroundColor: '#059669',
    color: 'white',
    border: 'none',
    padding: isMobile ? '12px' : '14px',
    borderRadius: '10px',
    fontWeight: '600',
    cursor: 'pointer',
    width: '100%',
    marginTop: '16px',
    fontSize: isMobile ? '14px' : '15px',
  },
  labelSelector: {
    display: 'flex',
    gap: '8px',
    marginBottom: '16px',
  },
  labelOption: {
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    cursor: 'pointer',
    border: '1px solid #e2e8f0',
    backgroundColor: 'white',
    color: '#64748b',
  },
  labelOptionActive: {
    backgroundColor: '#ecfdf5',
    color: '#059669',
    borderColor: '#059669',
  },
});
