  export const styles = {
    topBar: {
      backgroundColor: '#064e3b',
      color: '#ecfdf5',
      fontSize: '12px',
      padding: '8px 0',
      fontFamily: '"Inter", sans-serif',
    },
    container: {
      maxWidth: '1200px',
      margin: '0 auto',
      padding: '0 20px',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    header: {
      backgroundColor: 'rgba(255, 255, 255, 0.95)',
      backdropFilter: 'blur(12px)',
      padding: '16px 0',
      borderBottom: '1px solid rgba(226, 232, 240, 0.6)',
      fontFamily: '"Inter", sans-serif',
      position: 'sticky',
      top: 0,
      zIndex: 1000,
      boxShadow: '0 4px 30px rgba(0, 0, 0, 0.03)',
    },
    headerContent: {
      display: 'flex',
      alignItems: 'center',
      gap: '40px',
    },
    logo: {
      fontFamily: '"DM Sans", sans-serif',
      fontSize: '28px',
      fontWeight: '800',
      background: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      textDecoration: 'none',
      letterSpacing: '-1px',
    },
    searchContainer: {
      flex: 1,
      position: 'relative',
      maxWidth: '500px',
    },
    searchInput: {
      width: '100%',
      padding: '14px 24px 14px 52px',
      borderRadius: '24px',
      border: '1px solid #e2e8f0',
      backgroundColor: '#f8fafc',
      fontSize: '14px',
      outline: 'none',
      transition: 'all 0.3s ease',
      fontFamily: '"Inter", sans-serif',
    },
    searchIcon: {
      position: 'absolute',
      left: '20px',
      top: '50%',
      transform: 'translateY(-50%)',
      color: '#94a3b8',
    },
    actions: {
      display: 'flex',
      alignItems: 'center',
      gap: '24px',
    },
    actionItem: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textDecoration: 'none',
      color: '#334155',
      fontSize: '12px',
      gap: '4px',
      transition: 'color 0.2s',
      cursor: 'pointer',
    },
    iconBox: {
      fontSize: '20px',
      position: 'relative',
    },
    badge: {
      position: 'absolute',
      top: '-8px',
      right: '-8px',
      backgroundColor: '#ef4444',
      color: 'white',
      fontSize: '10px',
      fontWeight: 'bold',
      width: '16px',
      height: '16px',
      borderRadius: '50%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    bottomBar: {
      backgroundColor: 'rgba(248, 250, 252, 0.9)',
      backdropFilter: 'blur(12px)',
      borderBottom: '1px solid rgba(226, 232, 240, 0.6)',
      padding: '12px 0',
      fontFamily: '"Inter", sans-serif',
    },
    addressBtn: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      color: '#475569',
      fontSize: '13px',
      cursor: 'pointer',
      background: 'white',
      border: '1px solid #e2e8f0',
      padding: '8px 16px',
      borderRadius: '50px',
      transition: 'all 0.2s',
      boxShadow: '0 2px 5px rgba(0,0,0,0.02)',
    },
    miniCart: {
      position: 'absolute',
      top: '100%',
      right: 0,
      width: '320px',
      backgroundColor: 'white',
      boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
      borderRadius: '12px',
      padding: '20px',
      zIndex: 1001,
      border: '1px solid #e2e8f0',
      animation: 'fadeIn 0.2s ease',
    },
    miniCartItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      marginBottom: '16px',
      paddingBottom: '16px',
      borderBottom: '1px solid #f1f5f9',
    },
    miniCartImg: {
      width: '60px',
      height: '60px',
      borderRadius: '8px',
      objectFit: 'cover',
    },
    miniCartInfo: {
      flex: 1,
    },
    miniCartTitle: {
      fontSize: '13px',
      fontWeight: '600',
      color: '#1e293b',
      marginBottom: '4px',
      lineHeight: '1.4',
    },
    miniCartPrice: {
      fontSize: '14px',
      fontWeight: '700',
      color: '#059669',
    },
    checkoutBtn: {
      width: '100%',
      padding: '12px',
      backgroundColor: '#059669',
      color: 'white',
      border: 'none',
      borderRadius: '8px',
      fontSize: '14px',
      fontWeight: '600',
      cursor: 'pointer',
      marginTop: '12px',
      display: 'block',
      textAlign: 'center',
      textDecoration: 'none',
    },
  };